name: Deploy Alerts using bicep multistage
variables:
   azureServiceConnection: 'Squadra12k-SEBL'
   Location: 'francecentral'
   resourceGroupName: 'rg-infra'
   metricsTemplate: 'deployMetricsAlerts.bicep'
   logsTemplate: 'deployLogsAlerts.bicep'
   activityTemplate: 'deployActivityAlerts.bicep'
   metricsParametersFilePath: '$(System.DefaultWorkingDirectory)/AlertsDefinitions/metricsAlerts.json'
   logsParametersFilePath: '$(System.DefaultWorkingDirectory)/AlertsDefinitions/logsAlerts.json'
   StorageAccountName: 'testparamdiag'
   NameContainer: 'paramdiag'
   SubscriptionId: '0410a600-1bea-44c9-b7ee-3e4847c6a600'
   templatePathBICEPST: '$(System.DefaultWorkingDirectory)/storageaccount.bicep'
   logWkspcResourceId: '/subscriptions/0410a600-1bea-44c9-b7ee-3e4847c6a600/resourceGroups/RG-TESTSEBL/providers/Microsoft.OperationalInsights/workspaces/Supervision'
pool:
  #name: Azure Pipelines
  name: Default
  #Default
  #demands: agent.name -equals mydockeragent

stages:
- stage: Audit
  jobs:
  - job: AuditDiag
    steps:
      - task: AzurePowerShell@5
        displayName: 'Params'
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptPath: PsScripts/auditparamDiag.ps1
          errorActionPreference: continue
          azurePowerShellVersion: LatestVersion  
      - task: AzurePowerShell@5
        displayName: 'Resources'
        inputs:
          azureSubscription: $(azureServiceConnection)
          ScriptPath: PsScripts/Auditresource.ps1
          errorActionPreference: continue
          azurePowerShellVersion: LatestVersion
      - task: AzurePowerShell@5
        displayName: 'Extensions'
        inputs:
          azureSubscription: $(azureServiceConnection)
          ScriptPath: PsScripts/AuditExtensions.ps1
          errorActionPreference: continue
          azurePowerShellVersion: LatestVersion
      - task: AzurePowerShell@5
        displayName: 'Logs and Metrics'
        inputs:
          azureSubscription: $(azureServiceConnection)
          ScriptPath: PsScripts/Auditmetrique.ps1
          errorActionPreference: continue
          azurePowerShellVersion: LatestVersion

- stage: MatrixGenerationAndDeployrunEnv
  jobs:
  - job: MatrixGen
    steps:
      - checkout : none
      - task: PowerShell@2
        displayName: 'Metrics Alerts Generation'
        inputs:
         pwsh: true
         filePath: '$(Agent.BuildDirectory)/s/PsScripts/metricMatrixGen.ps1'
       #arguments:
        #  -typeOfAlertstoFormat 'metrics'
         # -baseDir '$(System.DefaultWorkingDirectory)'
      - task: AzureCLI@2
        displayName: 'Log matrix gen'
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: batch
          scriptLocation: inlineScript
          inlineScript: |
           az version
      - task: AzureCLI@2
        displayName: 'Admin alerts matrix gen'
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: batch
          scriptLocation: inlineScript
          inlineScript: |
           az version
      - task: AzurePowerShell@5
        displayName: 'Get Diagnostics Params'
        inputs:
          azureSubscription: $(azureServiceConnection)
          ScriptPath: PsScripts/GetdiagSettingCategory.ps1
          errorActionPreference: continue
          azurePowerShellVersion: LatestVersion
      - task: AzurePowerShell@5
        displayName: 'Diagnostics Params settings gen'
        inputs:
          azureSubscription: $(azureServiceConnection)
          ScriptPath: PsScripts/Matriceclientdiag.ps1
          errorActionPreference: continue
          azurePowerShellVersion: LatestVersion
  - job: ValidateRunEnv
    pool: server
    dependsOn: MatrixGen
    steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440 # matrix ruploaded to storage account and validated
        
        inputs:
         notifyUsers: |
            sebastien.dillier@squadra-run.com
            sebastien.leroy@squadra-run.com
            romain.rodrigues@squadra-run.com
            
         instructions: 'Please validate the build in order to deploy RG and storage accounts and LAW on customer infra'
         onTimeout: 'resume' 
  - job: DeployRunEnv
    dependsOn: ValidateRunEnv
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Deploy Resource Group and LAW-storage account'
        inputs:
          azureResourceManagerConnection: $(azureServiceConnection)
          subscriptionId: $(SubscriptionId)
          resourceGroupName: $(resourceGroupName)
          location: 'France Central'
          csmFile: '$(System.DefaultWorkingDirectory)/loganalytics.bicep'
          deploymentName: rgandlog    

- stage: Deploy
  jobs:
  - job: DeployDiagsParams
    steps:
    - task: AzurePowerShell@5
      displayName: 'Deploy Diags Paramas'
      inputs:
        azureSubscription: $(azureServiceConnection)
        ScriptPath: PsScripts/DeployParamDiag.ps1
        errorActionPreference: continue
        azurePowerShellVersion: LatestVersion
  - job: DeployActionGroups
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Action Groups'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: batch
        scriptLocation: inlineScript
        inlineScript: |
         az version
        
- stage: ConvertCSV2Json
  jobs:
  - job: ConvertMetricsAlertsCSVToJson
    steps:  
       - task: AzureCLI@2
         displayName: 'Deploy Action Groups'
         inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: batch
          scriptLocation: inlineScript
          inlineScript: |
           az version
  - job: ConvertLogsAlertsCSVToJson
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: batch
          scriptLocation: inlineScript
          inlineScript: |
           az version
  - job: ConvertActivityLogsAlertsCSVToJson
    steps:
     - task: AzureCLI@2
       displayName: 'Deploy Action Groups'
       inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: batch
        scriptLocation: inlineScript
        inlineScript: |
            az version 
  - job: DevelopWaitingApproval
    dependsOn: ConvertMetricsAlertsCSVToJson
    pool: server
    timeoutInMinutes: 4320 # 3 days

- stage: DeployAlerts
  dependsOn: ConvertCSV2Json
  jobs:
  - job: DeployAllAlertsTypes
    steps:
    - checkout: none
    - task: AzureCLI@2
      displayName: 'Deploy Action Groups'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: batch
        scriptLocation: inlineScript
        inlineScript: |
            az version

- stage: AuditFinal
  jobs:
  - job: DiagFinal
    steps:
    - task: AzurePowerShell@5
      displayName: 'Audit Final Param Diag'
      inputs:
        azureSubscription: $(azureServiceConnection)
        ScriptPath: PsScripts/auditfinaldiag.ps1
        errorActionPreference: continue
        azurePowerShellVersion: LatestVersion
  - job: MetriqueFinal
    steps:
    - task: AzurePowerShell@5
      displayName: 'Audit Final Metrique'
      inputs:
        azureSubscription: $(azureServiceConnection)
        ScriptPath: PsScripts/PsScripts/AuditFinalMetrique.ps1
        errorActionPreference: continue
        azurePowerShellVersion: LatestVersion
  - job: ResourceFinal
    steps:
    - task: AzurePowerShell@5
      displayName: 'Audit Final Resource'
      inputs:
        azureSubscription: $(azureServiceConnection)
        ScriptPath: PsScripts/PsScripts/AuditFinalResource.ps1
        errorActionPreference: continue
        azurePowerShellVersion: LatestVersion

