name: Deploy Alerts using bicep multistage
variables:
   azureServiceConnection: 'SC-Squadra12K€'
   resourceGroupName: 'rg-infra'
   metricsTemplate: 'deployMetricsAlerts.bicep'
   logsTemplate: 'deployLogsAlerts.bicep'
   activityTemplate: 'deployActivityAlerts.bicep'
   metricsParametersFilePath: '$(System.DefaultWorkingDirectory)/AlertsDefinitions/metricsAlerts.json'
   logsParametersFilePath: '$(System.DefaultWorkingDirectory)/AlertsDefinitions/logsAlerts.json'
pool:
  #name: Azure Pipelines
  name: Default
  #Default
  #demands: agent.name -equals mydockeragent

stages:
- stage: Audit
  jobs:
  - job: AuditDiag
    steps:
      - task: AzureCLI@2
        displayName: 'Audit Diag Params'
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
           az version
      - task: AzureCLI@2
        displayName: 'Audit Resources'
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
           az version
      - task: AzureCLI@2
        displayName: 'Audit Resources'
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
           az version
      - task: AzureCLI@2
        displayName: 'Audit Resources'
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
           az version

- stage: ActionGroups


  jobs:
  - job: DeployActionGroups
    steps:
    
    - task: AzureCLI@2
      displayName: 'Deploy Action Groups'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
         az version
        
- stage: ConvertCSV2Json
  jobs:
  - job: ConvertMetricsAlertsCSVToJson
    steps:

          
       - task: AzureCLI@2
         displayName: 'Deploy Action Groups'
         inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
           az version
   
  - job: ConvertLogsAlertsCSVToJson
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: $(azureServiceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
           az version
  - job: ConvertActivityLogsAlertsCSVToJson
    steps:
     - task: AzureCLI@2
       displayName: 'Deploy Action Groups'
       inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
            az version
    
  - job: DevelopWaitingApproval
    dependsOn: ConvertMetricsAlertsCSVToJson
    pool: server
    timeoutInMinutes: 4320 # 3 days

- stage: DeployAlerts

  dependsOn: ConvertCSV2Json
  jobs:
  - job: DeployAllAlertsTypes
    steps:
    - checkout: none
    - task: AzureCLI@2
      displayName: 'Deploy Action Groups'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
            az version

