name: Deploy Alerts using bicep staging
variables:
   azureServiceConnection: 'SC-MPNSeb'
   resourceGroupName: 'supervisionbiceppoc'
   metricsTemplate: 'deployMetricsAlerts.bicep'
   logsTemplate: 'deployLogsAlerts.bicep'
   metricsParametersFilePath: '$(System.DefaultWorkingDirectory)/AlertsDefinitions/metricsAlerts.json'
   logsParametersFilePath: '$(System.DefaultWorkingDirectory)/AlertsDefinitions/logsAlerts.json'
pool:
  name: Default

stages:
- stage: DeployMetricsAlerts
  jobs:
  - job: PowerhsellDeploy
    steps:
    - task: PowerShell@2
      inputs:
       pwsh: true
       targetType: inline
       script: | 
        write-host "hello"

  - job: DevelopWaitingApproval
    dependsOn: DevelopValidate
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days

    steps:

    - task: ManualValidation@0
      displayName: WaitingApproval
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          'sebastien.dillier@squadra-run.com'
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'
   
      


