name: Deploy Alerts using bicep multistage
variables:
   azureServiceConnection: 'SC-MPNSeb'
   resourceGroupName: 'supervisionbiceppoc'
   metricsTemplate: 'deployMetricsAlerts.bicep'
   logsTemplate: 'deployLogsAlerts.bicep'
   metricsParametersFilePath: '$(System.DefaultWorkingDirectory)/AlertsDefinitions/metricsAlerts.json'
   logsParametersFilePath: '$(System.DefaultWorkingDirectory)/AlertsDefinitions/logsAlerts.json'
pool:
  name: Default

stages:
- stage: DeployMetricsAlerts
  jobs:
  - job: PowerhsellDeploy
    steps:
    - task: PowerShell@2
      inputs:
       pwsh: true
       scriptPath: '$(Build.SourcesDirectory)/formatMetrics.ps1'
       arguments:
          -typeOfAlertstoFormat 'Logs' #$(Prefix)
          
      

  - job: DevelopWaitingApproval
    dependsOn: PowerhsellDeploy
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days

    steps:

    - task: ManualValidation@0
      displayName: WaitingApproval
      
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          sebastien.dillier@squadra-run.com
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'
   
      


- stage: DeployLogsAlerts
  jobs:
  - job: PowerhsellDeploy2
    steps:
    - task: PowerShell@2
      inputs:
       pwsh: true
       targetType: inline
       script: | 
        write-host "hello jobstage2"

  - job: DevelopWaitingApproval
    dependsOn: PowerhsellDeploy2
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days

- stage: DeployAcitivtylogsAlerts
  jobs:
  - job: PowerhsellDeploy2
    steps:
    - task: PowerShell@2
      inputs:
       pwsh: true
       targetType: inline
       script: | 
        write-host "hello jobstage2"

  - job: DevelopWaitingApproval
    dependsOn: PowerhsellDeploy2
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days
