name: Deploy Alerts using bicep multistage
variables:
   azureServiceConnection: 'SC-MPNSeb'
   resourceGroupName: 'supervisionbiceppoc'
   metricsTemplate: 'deployMetricsAlerts.bicep'
   logsTemplate: 'deployLogsAlerts.bicep'
   metricsParametersFilePath: '$(System.DefaultWorkingDirectory)/AlertsDefinitions/metricsAlerts.json'
   logsParametersFilePath: '$(System.DefaultWorkingDirectory)/AlertsDefinitions/logsAlerts.json'
pool:
  name: Default

stages:
- stage: ConvertCSV2Json
  jobs:
  - job: ConvertMetricsAlertsCSVToJson
    steps:
    - task: PowerShell@2
      inputs:
       pwsh: true
       #scriptPath: '$(System.DefaultWorkingDirectory)/formatMetrics.ps1'
       filePath: '$(Agent.BuildDirectory)/s/formatMetrics.ps1'
       arguments:
          -typeOfAlertstoFormat 'metrics'
          -baseDir '$(System.DefaultWorkingDirectory)'
  - job: ConvertLogsAlertsCSVToJson
    steps:
    - task: PowerShell@2
      inputs:
       pwsh: true
       #scriptPath: '$(System.DefaultWorkingDirectory)/formatMetrics.ps1'
       filePath: '$(Agent.BuildDirectory)/s/formatMetrics.ps1'
       arguments:
          -typeOfAlertstoFormat 'logs' 
          -baseDir '$(System.DefaultWorkingDirectory)'   

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)'
        artifact: 'ParametersFiles'
        publishLocation: 'pipeline'
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'ParametersFiles'
        targetPath: '$(System.DefaultWorkingDirectory)'
        patterns: '**'
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          ls -R $(System.DefaultWorkingDirectory)
          #cat $(Pipeline.Workspace)/AlertsDefinitions/logsAlerts.json
          cat $(System.DefaultWorkingDirectory)/AlertsDefinitions/logsAlerts.json
          
  - job: DevelopWaitingApproval
    dependsOn: ConvertMetricsAlertsCSVToJson
    pool: server
    timeoutInMinutes: 4320 # 3 days

    #steps:

    #- task: ManualValidation@0
    #  displayName: WaitingApproval
    #  
    #  timeoutInMinutes: 1440 # task times out in 1 day
    #  inputs:
    #    notifyUsers: |
    #      sebastien.dillier@squadra-run.com
    #    instructions: 'Please validate the build configuration and resume'
    #    onTimeout: 'resume'
   
      


- stage: DeployAlerts
  dependsOn: ConvertCSV2Json
  jobs:
  - job: DeployMetricAlerts
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'ParametersFiles'
        targetPath: '$(System.DefaultWorkingDirectory)'
        patterns: '**'

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          ls -R $(System.DefaultWorkingDirectory)
          cat $(System.DefaultWorkingDirectory)/AlertsDefinitions/logsAlerts.json
          #ls $(Build.SourcesDirectory)
          #cat $(Build.SourcesDirectory)/AlertsDefinitions/metricsAlerts.json
          az deployment group create --resource-group $(resourceGroupName) --template-file $(metricsTemplate) --parameters $(System.DefaultWorkingDirectory)/AlertsDefinitions/metricsAlerts.json
  - job: DeployLogsAlerts
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          echo $(logsParametersFilePath)
          cat $(logsParametersFilePath)
          cat $(Build.SourcesDirectory)/AlertsDefinitions/logsAlerts.json
          az deployment group create --resource-group $(resourceGroupName) --template-file $(logsTemplate) --parameters $(System.DefaultWorkingDirectory)/AlertsDefinitions/logsAlerts.json
              